'use client';
import {ChangeEvent,FormEvent,useEffect,useState} from 'react';import{useRouter}from'next/navigation';
import{StaffAction,StaffBadge,StaffLoading,StaffNotice,StaffPage,StaffPageHeader,StaffPageInner,StaffPanel,StaffSectionHeader}from'@/components/StaffPortalUI';
type Staff={laurem_id:string|null;employee_number:string;full_name:string;email:string;phone:string|null;job_title:string;employment_status:string;start_date:string|null;location:string|null;portal_address:string|null;address_line_1:string|null;address_line_2:string|null;city:string|null;county:string|null;postcode:string|null;country:string|null;profile_photo_path:string|null;profile_photo_url?:string};
function initials(name:string){return name.split(' ').map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase();}
export default function StaffProfilePage(){
 const router=useRouter();const[staff,setStaff]=useState<Staff|null>(null);const[phone,setPhone]=useState('');const[address1,setAddress1]=useState('');const[address2,setAddress2]=useState('');const[city,setCity]=useState('');const[county,setCounty]=useState('');const[postcode,setPostcode]=useState('');const[country,setCountry]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[photoBusy,setPhotoBusy]=useState(false);const[photoFailed,setPhotoFailed]=useState(false);const[error,setError]=useState('');const[saved,setSaved]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/me',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load your profile.');const n=b.staff as Staff;setStaff(n);setPhone(n.phone||'');setAddress1(n.address_line_1||'');setAddress2(n.address_line_2||'');setCity(n.city||'');setCounty(n.county||'');setPostcode(n.postcode||'');setCountry(n.country||'');setPhotoFailed(false);}catch(e){setError(e instanceof Error?e.message:'Unable to load your profile.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setSaved(false);setError('');try{const r=await fetch('/api/staff/me',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({phone,address_line_1:address1,address_line_2:address2,city,county,postcode,country})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to save your profile.');setStaff(b.staff);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Unable to save your profile.');}finally{setBusy(false);}}
 async function uploadPhoto(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setPhotoBusy(true);setError('');try{const fd=new FormData();fd.append('photo',f);const r=await fetch('/api/staff/me',{method:'POST',body:fd});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to upload photograph.');setStaff(b.staff);}catch(e){setError(e instanceof Error?e.message:'Unable to upload photograph.');}finally{setPhotoBusy(false);e.target.value='';}}
 if(loading)return <StaffLoading label="Loading your profile…"/>;
 if(!staff)return <StaffPage><StaffPageInner><StaffNotice tone="danger"><strong>Profile unavailable</strong><p>{error}</p><StaffAction onClick={()=>void load()}>Try again</StaffAction></StaffNotice></StaffPageInner></StaffPage>;
 return <StaffPage className="staff-page--profile"><StaffPageInner><StaffPageHeader eyebrow="LAUREM Care" title="My Profile" subtitle="Maintain your current contact and address information while LAUREM controls your employment identity." actions={<><StaffAction href="/staff/documents">Documents</StaffAction><StaffAction href="/staff/availability">Work preferences</StaffAction><StaffAction href="/staff/change-password" primary>Security</StaffAction></>}/>{error&&<StaffNotice tone="danger"><strong>Profile update failed</strong><p>{error}</p></StaffNotice>}
 <div className="staff-profile-grid"><div className="staff-profile-main"><StaffPanel className="staff-profile-identity"><div className="staff-profile-hero"><div className="staff-profile-avatar">{staff.profile_photo_url&&!photoFailed?<img src={staff.profile_photo_url} alt="LAUREM staff photograph" onError={()=>setPhotoFailed(true)}/>:<span>{initials(staff.full_name||'?')}</span>}</div><div><StaffBadge tone={staff.employment_status==='active'?'live':'attention'}>{staff.employment_status}</StaffBadge><h2>{staff.full_name}</h2><p>{staff.job_title}</p></div></div><div className="staff-profile-facts"><Fact label="LAUREM ID" value={staff.laurem_id||'Not set'}/><Fact label="Employee number" value={staff.employee_number}/><Fact label="Email" value={staff.email}/><Fact label="Start date" value={staff.start_date||'Not set'}/><Fact label="Work location" value={staff.location||'Not set'}/></div><p className="staff-card-copy">Employment identity fields are maintained by LAUREM Admin / HR and cannot be changed here.</p></StaffPanel>
 <StaffPanel><StaffSectionHeader title="Contact & address" copy="Keep these details current so LAUREM can reach you and maintain your employment records."/><form className="staff-modern-form" onSubmit={save}><label className="staff-form-field"><span className="staff-form-label">Phone</span><input className="staff-form-input" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={40} required/></label><label className="staff-form-field"><span className="staff-form-label">Address line 1</span><input className="staff-form-input" value={address1} onChange={e=>setAddress1(e.target.value)} maxLength={160}/></label><label className="staff-form-field"><span className="staff-form-label">Address line 2</span><input className="staff-form-input" value={address2} onChange={e=>setAddress2(e.target.value)} maxLength={160}/></label><div className="staff-form-grid"><label className="staff-form-field"><span className="staff-form-label">Town / City</span><input className="staff-form-input" value={city} onChange={e=>setCity(e.target.value)} maxLength={100}/></label><label className="staff-form-field"><span className="staff-form-label">County / Region</span><input className="staff-form-input" value={county} onChange={e=>setCounty(e.target.value)} maxLength={100}/></label><label className="staff-form-field"><span className="staff-form-label">Postcode</span><input className="staff-form-input" value={postcode} onChange={e=>setPostcode(e.target.value)} maxLength={20}/></label><label className="staff-form-field"><span className="staff-form-label">Country</span><input className="staff-form-input" value={country} onChange={e=>setCountry(e.target.value)} maxLength={80}/></label></div><div className="staff-form-actions"><StaffAction primary type="submit" disabled={busy}>{busy?'Saving…':'Save profile'}</StaffAction>{saved&&<span className="staff-save-confirmation">Saved.</span>}</div></form></StaffPanel></div>
 <aside><StaffPanel className="staff-profile-photo"><StaffSectionHeader title="Staff photograph" copy="Use a clear current photograph for your internal staff record."/><div className="staff-profile-photo-frame">{staff.profile_photo_url&&!photoFailed?<img src={staff.profile_photo_url} alt="LAUREM staff photograph" onError={()=>setPhotoFailed(true)}/>:<span>{initials(staff.full_name||'?')}</span>}</div><label className="staff-form-field"><span className="staff-form-label">{photoBusy?'Uploading photograph…':'Choose a photograph'}</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadPhoto} disabled={photoBusy}/></label><p className="staff-card-copy">JPG, PNG or WebP, maximum 5 MB. The photograph is private and served only to your authenticated staff session.</p></StaffPanel></aside></div>
 </StaffPageInner></StaffPage>;
}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
