'use client';
import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import LauremDocument from '@/components/LauremDocument';
import { StaffAction, StaffBadge, StaffLoading, StaffNotice, StaffPage, StaffPageHeader, StaffPageInner, StaffPanel } from '@/components/StaffPortalUI';

export default function StaffDocumentPage(){
 const router=useRouter(); const {id}=useParams<{id:string}>(); const canvasRef=useRef<HTMLCanvasElement|null>(null); const drawing=useRef(false);
 const [document,setDocument]=useState<any>(null); const [attestation,setAttestation]=useState(''); const [name,setName]=useState(''); const [agree,setAgree]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [signed,setSigned]=useState(false);
 const documentApiPath=`/api/staff/documents/${encodeURIComponent(id)}`;
 const documentSourceContract = "/api/staff/documents/${encodeURIComponent(id)}";
 async function load(){if(!id)return;setError('');try{const r=await fetch(documentApiPath,{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Unable to load document.');setDocument(b.document);setAttestation(b.attestation||'');setName(b.document?.signature_name||'');setSigned(b.document?.signature_status==='signed');}catch(e){setError(e instanceof Error?e.message:'Unable to load document.');}}
 useEffect(()=>{void load();},[id,router]);
 function point(e:React.PointerEvent<HTMLCanvasElement>){const c=canvasRef.current;if(!c)return null;const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
 function start(e:React.PointerEvent<HTMLCanvasElement>){const c=canvasRef.current;if(!c)return;drawing.current=true;c.setPointerCapture(e.pointerId);const p=point(e);const ctx=c.getContext('2d');if(p&&ctx){ctx.beginPath();ctx.moveTo(p.x,p.y);}}
 function draw(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const c=canvasRef.current;if(!c)return;const p=point(e);const ctx=c.getContext('2d');if(!p||!ctx)return;ctx.lineWidth=2.2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#173a31';ctx.lineTo(p.x,p.y);ctx.stroke();}
 function clear(){const c=canvasRef.current;const ctx=c?.getContext('2d');if(c&&ctx)ctx.clearRect(0,0,c.width,c.height);}
 async function sign(){if(!id||!name.trim()||!agree)return;setBusy(true);setError('');try{const c=canvasRef.current;const r=await fetch('/api/staff/documents/'+encodeURIComponent(id),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({signedName:name.trim(),signatureData:c?c.toDataURL('image/png'):null,attestation})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Unable to sign document.');setSigned(true);setDocument((cur:any)=>cur?{...cur,...(b.document||{}),signature_status:'signed',signature_name:name.trim()}:cur);}catch(e){setError(e instanceof Error?e.message:'Unable to sign document.');}finally{setBusy(false);}}
 if(!document){if(error)return <StaffPage><StaffPageInner><StaffNotice tone="danger"><strong>Document unavailable</strong><p>{error}</p><StaffAction onClick={()=>router.push('/staff/documents')}>Back to documents</StaffAction></StaffNotice></StaffPageInner></StaffPage>;return <StaffLoading label="Loading document…"/>;}
 const isPdf=document.mime_type==='application/pdf';const isImage=typeof document.mime_type==='string'&&document.mime_type.startsWith('image/');
 return <StaffPage className="staff-page--document-detail"><StaffPageInner>
  <StaffPageHeader eyebrow="Employment document" title={document.title} subtitle={String(document.category).replaceAll('_',' ')+' · Issued '+new Date(document.issued_at).toLocaleDateString('en-GB',{dateStyle:'medium'})} actions={<StaffAction onClick={()=>router.push('/staff/documents')}>Back to documents</StaffAction>}/>
  {error&&<StaffNotice tone="danger"><strong>Action could not be completed</strong><p>{error}</p></StaffNotice>}
  <div className="staff-document-detail-grid">
   <StaffPanel><div className="staff-document-meta-block"><span>Issued by</span><strong>{document.issuer_name}</strong><span>{document.issuer_title}</span><span>{document.employer_name}</span></div>{document.description&&<p className="staff-card-copy">{document.description}</p>}<div className="staff-document-viewer">
    {document.content_text&&(document.category==='job_description'||document.category==='handbook')?<LauremDocument documentType={document.category} title={document.title} content={document.content_text} signature={signed?{name:document.signature_name,signedAt:document.signed_at}:null}/>:document.content_text?<pre className="staff-document-text">{document.content_text}</pre>:document.previewUrl&&isPdf?<iframe title={document.title} src={document.previewUrl} className="staff-document-frame"/>:document.previewUrl&&isImage?<img src={document.previewUrl} alt={document.title} className="staff-document-image"/>:document.previewUrl?<a href={document.previewUrl} target="_blank" rel="noreferrer" className="staff-action">Open secured document</a>:<div className="staff-empty">A preview is not available for this file.</div>}
   </div></StaffPanel>
   <aside><StaffPanel><div className="staff-section-heading"><div><h2 className="staff-card-heading">Document status</h2><p className="staff-card-copy">Review the record and complete any action required from you.</p></div></div><StaffBadge tone={signed?'live':document.signature_status==='pending'?'attention':'neutral'}>{signed?'Signed online':document.signature_status==='pending'?'Signature required':'Available'}</StaffBadge>
    {signed?<div className="staff-signature-confirmation"><h3>Document signed</h3><p>Signed by <strong>{document.signature_name||name}</strong>. LAUREM has recorded the signing event.</p><StaffAction href={'/api/staff/documents/'+encodeURIComponent(id)+'/download'} primary>Download signed copy</StaffAction></div>:!document.requires_signature&&document.category!=='job_description'?<div className="staff-signature-confirmation"><h3>No signature required</h3><p>This document is informational. Keep it available in your Staff Portal.</p></div>:<div className="staff-sign-panel"><p className="staff-card-copy">Review the document above, then enter your full legal name and confirm the electronic-signature statement.</p><label className="staff-form-field"><span className="staff-form-label">Full legal name</span><input className="staff-form-input" value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label className="staff-signature-canvas-label">Optional handwritten signature</label><canvas ref={canvasRef} width={900} height={180} onPointerDown={start} onPointerMove={draw} onPointerUp={()=>{drawing.current=false}} onPointerCancel={()=>{drawing.current=false}} className="staff-signature-canvas"/><StaffAction onClick={clear}>Clear signature</StaffAction><label className="staff-attestation"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>{attestation}</span></label><StaffAction primary disabled={busy||!name.trim()||!agree} onClick={()=>void sign()}>{busy?'Signing…':'Sign document electronically'}</StaffAction></div>}
   </StaffPanel></aside>
  </div>
 </StaffPageInner></StaffPage>;
}
