import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getStaffSession } from '@/lib/laurem-staff-auth';
import { recordLauremAuditEvent } from '@/lib/laurem-audit';
import { LAUREM_CARE_SETTINGS, LAUREM_SHIFT_PREFERENCES, LAUREM_WORK_REGIONS, LAUREM_TRAINING_LOCATIONS } from '@/lib/laurem-staff-operations';
const parseDate=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(new Date(v+'T00:00:00Z').getTime())?v:null;
const clean=(v:unknown,a:readonly string[])=>Array.isArray(v)?[...new Set(v.filter((x):x is string=>typeof x==='string').map(x=>x.trim()).filter(x=>a.includes(x)))]:[];
export async function GET(request:NextRequest){const s=await getStaffSession(request);if(!s)return NextResponse.json({error:'Unauthorised'},{status:401});const{data,error}=await db().from('laurem_staff_rota_requests').select('id,effective_from,stable_shift_preference,regions,shift_preferences,care_settings,preferred_training_location,driver_available,notes,status,review_note,reviewed_at,created_at,updated_at').eq('staff_id',s.staff_id).order('effective_from',{ascending:false}).order('created_at',{ascending:false}).limit(50);if(error)return NextResponse.json({error:'Unable to load your rota preferences.'},{status:500});return NextResponse.json({current:(data||[])[0]||null,history:data||[]});}
export async function POST(request:NextRequest){const s=await getStaffSession(request);if(!s)return NextResponse.json({error:'Unauthorised'},{status:401});const b=await request.json().catch(()=>null) as Record<string,unknown>|null;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London'}).format(new Date());const effective=parseDate(b?.effectiveFrom)||today;if(effective<today)return NextResponse.json({error:'Rota preferences cannot be backdated.'},{status:400});const regions=clean(b?.regions,LAUREM_WORK_REGIONS);const shifts=clean(b?.shiftPreferences,LAUREM_SHIFT_PREFERENCES.map(x=>x.key));const settings=clean(b?.careSettings,LAUREM_CARE_SETTINGS.map(x=>x.key));const trainingLocation=typeof b?.trainingLocation==='string'&&LAUREM_TRAINING_LOCATIONS.includes(b.trainingLocation as typeof LAUREM_TRAINING_LOCATIONS[number])?b.trainingLocation:null;if(!regions.length||!shifts.length||!settings.length)return NextResponse.json({error:'Select at least one region, shift preference and care setting.'},{status:400});if(!trainingLocation)return NextResponse.json({error:'Select one training location.'},{status:400});const payload={staff_id:s.staff_id,effective_from:effective,stable_shift_preference:b?.stableShift!==false,regions,shift_preferences:shifts,care_settings:settings,preferred_training_location:trainingLocation,driver_available:b?.driverAvailable===true,notes:typeof b?.notes==='string'?b.notes.trim().slice(0,3000):null,status:'requested',reviewed_by:null,reviewed_at:null,review_note:null,updated_at:new Date().toISOString()};const client=db();const ex=await client.from('laurem_staff_rota_requests').select('id').eq('staff_id',s.staff_id).eq('effective_from',effective).maybeSingle();const r=ex.data?.id?await client.from('laurem_staff_rota_requests').update(payload).eq('id',ex.data.id).select('*').single():await client.from('laurem_staff_rota_requests').insert(payload).select('*').single();if(r.error||!r.data)return NextResponse.json({error:'Unable to save your rota request.'},{status:500});await recordLauremAuditEvent({lifecycleArea:'workforce',entityType:'laurem_staff_rota_requests',entityId:r.data.id,staffId:s.staff_id,actorType:'staff',actor:s.email,action:ex.data?.id?'rota_request_updated':'rota_request_created',newState:r.data.status,metadata:{effectiveFrom:effective,regions,shiftPreferences:shifts,careSettings:settings,trainingLocation,stableShift:payload.stable_shift_preference,driverAvailable:payload.driver_available}});return NextResponse.json({rota:r.data},{status:ex.data?.id?200:201});}
