'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { moneyGbp, visaPathwayLabel, type LauremVisaPathway } from '@/lib/laurem-visa-sponsorship';
import { LAUREM_COUNTRY_OPTIONS, normalisePassportCountry } from '@/lib/laurem-country-options';
import { LAUREM_CURRENT_UK_VISA_TYPES } from '@/lib/laurem-visa-options';
import { LAUREM_PAYMENT_BANK_DETAILS } from '@/lib/laurem-payment-details';
import { StaffAction, StaffBadge, StaffLoading, StaffMetric, StaffNotice, StaffPage, StaffPageHeader, StaffPageInner, StaffPanel, StaffSectionHeader } from '@/components/StaffPortalUI';

type Readiness={ready:boolean;readyForSmsSubmission:boolean;items:{key:string;label:string;ready:boolean}[];missing:string[]};
type Data={staff:any;application:any;applicationAddresses:string[];recommendation:{pathway:LauremVisaPathway;basis:string;label:string};case:any;invoice:any;events:any[];readiness:Readiness|null;visaDocuments:any[];cosStatus:{key:string;label:string;canDownload:boolean};request:{available:boolean;pathway:LauremVisaPathway|null;paymentPlanKind:'uk_switch_split'|'full_upfront';label:string|null;explanation:string};sponsorshipOccupation:{code:string;title:string}|null;sponsorshipTermEndDate:string|null;sponsorshipTermEndDateLabel:string|null};

function fmt(v:any){if(!v)return'Not set';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});}
function tone(status:string){return status==='active'||status==='completed'||status==='paid'?'live':status==='declined'||status==='withdrawn'||status==='failed'?'danger':status==='processing'||status==='pending'?'attention':'neutral';}
function Info({label,value}:{label:string;value:any}){return <div className="staff-visa-info"><span>{label}</span><strong>{value||'Not recorded'}</strong></div>;
}
function BankTransferInstructions({amount, paymentReference}:{amount:number;paymentReference:string}){
 const rows=[['Amount',moneyGbp(amount)],['Payee',LAUREM_PAYMENT_BANK_DETAILS.accountName],['Global account',LAUREM_PAYMENT_BANK_DETAILS.globalAccount],['Sort code',LAUREM_PAYMENT_BANK_DETAILS.sortCode],['SWIFT / BIC',LAUREM_PAYMENT_BANK_DETAILS.swiftBic],['IBAN',LAUREM_PAYMENT_BANK_DETAILS.iban],['Bank country',LAUREM_PAYMENT_BANK_DETAILS.bankCountry],['Bank name',LAUREM_PAYMENT_BANK_DETAILS.bankName],['Bank address',LAUREM_PAYMENT_BANK_DETAILS.bankAddress]];
 return <div style={{marginTop:14,padding:16,border:'1px solid var(--line)',borderRadius:12,background:'#fafcfb'}}><div className="staff-eyebrow">Bank transfer payment</div><h3 style={{margin:'4px 0 6px'}}>Pay by bank transfer</h3><p className="staff-card-copy">Use the account details below and enter the payment reference exactly as shown. No hosted card-payment link is required.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:12}}>{rows.map(([label,value])=><div key={label}><div className="staff-document-category">{label}</div><strong style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{value}</strong></div>)}</div><label className="staff-form-field" style={{marginTop:14}}><span className="staff-form-label">Payment reference</span><input className="staff-form-input" readOnly value={paymentReference||'LAUREM ID will be assigned automatically'}/><span className="staff-card-copy">This reference is automatically populated from your LAUREM ID when the invoice is generated.</span></label></div>;
}
function YesNoSelect({id,label,value,onChange,required=true}:{id:string;label:string;value:string;onChange:(value:string)=>void;required?:boolean}){return <label className="staff-form-field"><span className="staff-form-label">{label}{required?' *':''}</span><select id={id} className="staff-form-input" value={value} onChange={e=>onChange(e.target.value)} required={required}><option value="">Select an answer</option><option value="yes">Yes</option><option value="no">No</option></select></label>;
}

export default function StaffVisaSponsorshipPage(){
 const router=useRouter();const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[routeChoice,setRouteChoice]=useState<LauremVisaPathway>('visa_switch');const[currentVisaType,setCurrentVisaType]=useState('');const[currentVisaStartDate,setCurrentVisaStartDate]=useState('');const[currentVisaEndDate,setCurrentVisaEndDate]=useState('');const[passportNumber,setPassportNumber]=useState('');const[passportExpiryDate,setPassportExpiryDate]=useState('');const[passportCountry,setPassportCountry]=useState('');const[addressIsCurrent,setAddressIsCurrent]=useState('');const[currentAddress,setCurrentAddress]=useState('');const[addressProofProvided,setAddressProofProvided]=useState('');const[rightToWorkStatus,setRightToWorkStatus]=useState('');const[rightToWorkProofProvided,setRightToWorkProofProvided]=useState('');const[ukStatusShareCode,setUkStatusShareCode]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/visa-sponsorship',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load visa sponsorship workspace.');setData(b);setRouteChoice(b.request?.pathway||b.recommendation.pathway);const info=b.case?.additional_information||{};setCurrentVisaType(info.current_visa_type||'');setCurrentVisaStartDate(info.current_visa_start_date||'');setCurrentVisaEndDate(info.current_visa_end_date||info.current_visa_expiry_date||'');setPassportNumber(info.passport_number||'');setPassportExpiryDate(info.passport_expiry_date||'');setPassportCountry(normalisePassportCountry(info.passport_country||''));setAddressIsCurrent(info.address_is_current||'');setCurrentAddress(info.current_address||'');setAddressProofProvided(info.address_proof_provided||'');setRightToWorkStatus(info.right_to_work_status||'');setRightToWorkProofProvided(info.right_to_work_provided||info.right_to_work_proof_provided||'');setUkStatusShareCode(info.uk_status_share_code||'');}catch(e){setError(e instanceof Error?e.message:'Unable to load visa sponsorship workspace.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 async function requestSupport(){setBusy(true);setError('');try{const r=await fetch('/api/staff/visa-sponsorship',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pathway:routeChoice})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to create visa support request.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create visa support request.');}finally{setBusy(false);}}
 async function saveInfo(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/staff/visa-sponsorship',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({currentVisaType,currentVisaStartDate,currentVisaEndDate,passportNumber,passportExpiryDate,passportCountry,addressIsCurrent,currentAddress,addressProofProvided,rightToWorkStatus,rightToWorkProofProvided,ukStatusShareCode})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to save visa information.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save visa information.');}finally{setBusy(false);}}
 if(loading)return <StaffLoading label="Loading visa support workspace…"/>;
 if(!data)return <StaffPage><StaffPageInner><StaffNotice tone="danger"><strong>Visa support workspace unavailable</strong><p>{error||'Unable to load visa support workspace.'}</p><StaffAction onClick={()=>void load()}>Try again</StaffAction></StaffNotice></StaffPageInner></StaffPage>;
 const c=data.case;const invoice=data.invoice;const splitPayment=data.request.paymentPlanKind==='uk_switch_split'||Number(invoice?.amount_pence)===50000;const paymentReference=invoice?.payment_reference||data.staff?.laurem_id||'';const upfrontAmount=splitPayment?500:2000;const isVisaSwitch=c?.pathway==='visa_switch';const showShareCode=isVisaSwitch&&(rightToWorkStatus==='no'||rightToWorkProofProvided==='no');
 return <StaffPage className="staff-page--visa"><StaffPageInner>
  <StaffPageHeader eyebrow="Immigration support" title="Visa Switch & Sponsorship" subtitle="Your LAUREM sponsorship workspace, case status, payment information, readiness and CoS records." actions={<><StaffAction onClick={()=>void load()}>Refresh</StaffAction><StaffAction href="/staff/messages">Message LAUREM</StaffAction></>}/>
  {error&&<StaffNotice tone="danger"><strong>Visa support update failed</strong><p>{error}</p></StaffNotice>}
  {data.sponsorshipOccupation&&<StaffPanel className="staff-visa-occupation"><div><p className="staff-eyebrow">Sponsored occupation</p><div className="staff-visa-occupation-main"><strong>{data.sponsorshipOccupation.code}</strong><span>{data.sponsorshipOccupation.title}</span></div><p className="staff-card-copy">This occupation code is derived from your LAUREM role and is used consistently across sponsorship and contract records. Final sponsorship remains subject to the applicable UK rules and the actual duties of the job.</p></div></StaffPanel>}
  <div className="staff-stat-grid"><StaffMetric label="Case" value={c?c.status.replaceAll('_',' '):'Not requested'}/><StaffMetric label="Route" value={c?visaPathwayLabel(c.pathway):data.request.label||'Not selected'}/><StaffMetric label="Occupation" value={data.sponsorshipOccupation?.code||'Not set'}/><StaffMetric label="Term" value={data.sponsorshipTermEndDateLabel||'Not calculated'}/></div>
  {!c?<StaffPanel className="staff-visa-request-panel">
    <StaffSectionHeader title="Request sponsorship support" copy={data.request.explanation}/>
    <StaffNotice><strong>Before you proceed</strong><p>Pressing the button below will create the applicable LAUREM service invoice and open your visa-switch case. For UK visa switches involving Healthcare Assistants, Senior Healthcare Assistants, Support Workers and Senior Support Workers, the initial service invoice is £500 and must be paid within 3 days of the invoice issue date before LAUREM begins the visa sponsorship process. The remaining £1,500 is not payable now and is recovered through weekly salary deductions during the first three months of employment, following successful visa approval and commencement of employment. International Nurses remain subject to the existing £2,000 arrangement.</p></StaffNotice>
    <div className="staff-visa-request-grid"><div><p className="staff-document-category">Planned LAUREM sponsorship term</p><h3>{data.sponsorshipTermEndDateLabel?'Three-year term ends '+data.sponsorshipTermEndDateLabel:'End date will be calculated when a commencement date is recorded'}</h3><p className="staff-card-copy">The planned sponsorship term is three years for LAUREM employment and sponsorship documentation. The final Certificate of Sponsorship (CoS) end date will be based on the approved sponsorship record.</p></div><div><p className="staff-document-category">Your route</p><h3>{routeChoice==='visa_switch'?'UK Visa Switch Support':'International Visa Sponsorship Support'}</h3><p className="staff-card-copy">{data.application.role_applied||data.staff.job_title}</p></div></div>
    <div className="staff-visa-request-actions"><StaffAction primary disabled={busy||!data.request.available} onClick={()=>void requestSupport()}>{busy?'Generating invoice…':'Request £'+upfrontAmount.toLocaleString('en-GB')+' Invoice'}</StaffAction><StaffAction href="/staff/documents">View documents</StaffAction></div>
  </StaffPanel>:<>
    <StaffPanel className="staff-visa-status-panel"><div className="staff-visa-status-top"><div><p className="staff-eyebrow">Certificate of Sponsorship</p><h2 className="staff-card-heading">CoS Status</h2><p className="staff-card-copy">Requested {fmt(c.requested_at)}</p></div><StaffBadge tone={tone(data.cosStatus.key)}>{data.cosStatus.label}</StaffBadge></div>
      {invoice&&<div className="staff-visa-invoice-strip"><strong>{moneyGbp(Number(invoice.amount_pence||200000))} invoice</strong><span>{invoice.invoice_number} · {invoice.status}</span><small>Issued {invoice.issue_date||'today'}{invoice.due_date?' · Due '+invoice.due_date:''}</small><small>Payment reference: <strong>{paymentReference||'Not assigned'}</strong></small></div>}
      <div className="staff-visa-actions">{data.cosStatus.canDownload&&data.visaDocuments[0]&&<a href={'/api/staff/documents/'+encodeURIComponent(data.visaDocuments[0].id)+'/download'} download className="staff-action-primary">Download COS</a>}<StaffAction href="/staff/messages">Message Admin / HR</StaffAction></div>
    </StaffPanel>
    <StaffPanel><StaffSectionHeader title={visaPathwayLabel(c.pathway)} copy={c.pathway_basis}/><div className="staff-visa-case-row"><StaffBadge tone={tone(c.status)}>{c.status.replaceAll('_',' ')}</StaffBadge><span>Requested {fmt(c.requested_at)}</span></div></StaffPanel>
    <div className="staff-workforce-grid"><StaffPanel><StaffSectionHeader title="Information already held" copy="These details come from your recruitment record and case information."/><div className="staff-visa-info-grid"><Info label="Full name" value={data.application.full_name}/><Info label="Date of birth" value={data.application.date_of_birth}/><Info label="Nationality" value={data.application.nationality}/><Info label="Current country" value={data.application.current_country||data.application.country_of_residence}/><Info label="Role applied for" value={data.application.role_applied||data.staff.job_title}/><Info label="Start date" value={data.application.start_date||data.staff.start_date}/><Info label="Living in UK" value={data.application.living_in_uk}/><Info label="Work permission" value={data.application.work_permission}/><Info label="Requires sponsorship" value={data.application.requires_sponsorship}/><Info label="Phone" value={data.application.phone}/><Info label="Email" value={data.application.email}/><Info label="Address" value={data.application.address}/></div></StaffPanel>
      <StaffPanel><StaffSectionHeader title="LAUREM invoice" copy="This is a LAUREM service invoice, not a UK government visa fee."/><div className="staff-visa-invoice-amount">{moneyGbp(Number(invoice?.amount_pence||200000))}</div><div className="staff-card-copy">{invoice?.invoice_number||'Invoice being prepared'} · Status {invoice?.status||'issued'} · Issued {invoice?.issue_date||'today'}{invoice?.due_date?' · Due '+invoice.due_date:''}</div><BankTransferInstructions amount={Number(invoice?.amount_pence||200000)} paymentReference={paymentReference}/>{splitPayment?<div className="staff-visa-payment-plan"><strong>UK visa switch payment plan</strong><p>£500 is due within 3 days of the invoice issue date. The remaining £1,500 is recovered after successful visa approval and commencement of employment through weekly salary deductions during the first three months, beginning with the first training week.</p><div><span>Weeks 1-12: <strong>£115.38 per week</strong></span><span>Week 13: <strong>£115.44 final deduction</strong></span><span>Total deferred: <strong>£1,500.00</strong></span></div></div>:<p className="staff-card-copy">This is the existing LAUREM service invoice arrangement. It is not presented as a UK government visa fee.</p>}<StaffAction onClick={()=>window.print()}>Print / Save invoice</StaffAction></StaffPanel></div>
    <StaffPanel><StaffSectionHeader title="Complete your sponsorship details" copy="These details are completed by you, the new hire. Enter the information exactly as shown on your current passport and UK immigration documents. LAUREM already has your recruitment information, so this section only confirms and updates sponsorship-specific details."/>
      <form className="staff-modern-form" onSubmit={saveInfo}>
        <div className="staff-form-grid">
          <label className="staff-form-field"><span className="staff-form-label">Passport number *</span><input className="staff-form-input" value={passportNumber} onChange={e=>setPassportNumber(e.target.value)} required autoComplete="off"/></label>
          <label className="staff-form-field"><span className="staff-form-label">Passport expiry *</span><input className="staff-form-input" type="date" value={passportExpiryDate} onChange={e=>setPassportExpiryDate(e.target.value)} required/></label>
          <label className="staff-form-field"><span className="staff-form-label">Passport country *</span><select className="staff-form-input" value={passportCountry} onChange={e=>setPassportCountry(e.target.value)} required><option value="">Select passport country</option>{LAUREM_COUNTRY_OPTIONS.map(option=><option key={option.code} value={option.code}>{option.name}</option>)}</select></label>
          <label className="staff-form-field"><span className="staff-form-label">{isVisaSwitch?'Current UK visa type *':'Current UK visa type'}</span><select className="staff-form-input" value={currentVisaType} onChange={e=>setCurrentVisaType(e.target.value)} required={isVisaSwitch}><option value="">Select your current UK visa type</option>{LAUREM_CURRENT_UK_VISA_TYPES.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>
          <label className="staff-form-field"><span className="staff-form-label">{isVisaSwitch?'Current UK visa start date *':'Current UK visa start date'}</span><input className="staff-form-input" type="date" value={currentVisaStartDate} onChange={e=>setCurrentVisaStartDate(e.target.value)} required={isVisaSwitch}/></label><label className="staff-form-field"><span className="staff-form-label">{isVisaSwitch?'Current UK visa end date *':'Current UK visa end date'}</span><input className="staff-form-input" type="date" value={currentVisaEndDate} onChange={e=>setCurrentVisaEndDate(e.target.value)} required={isVisaSwitch}/></label>
        </div>

        <div style={{marginTop:18,paddingTop:18,borderTop:'1px solid var(--line)'}}>
          <p className="staff-eyebrow">Address confirmation</p>
          <h3 style={{margin:'4px 0 6px'}}>Address(es) you entered during your application</h3>
          {!data.applicationAddresses?.length
            ? <p className="staff-card-copy">No application address is currently available in your recruitment record. Please provide your current address below.</p>
            : <div style={{display:'grid',gap:8}}>{data.applicationAddresses.map((address,index)=><div key={index} style={{padding:12,border:'1px solid var(--line)',borderRadius:10,whiteSpace:'pre-wrap'}}>{address}</div>)}</div>}
          <div className="staff-form-grid" style={{marginTop:12}}>
            <YesNoSelect id="address-is-current" label="Is the application address above still your current address?" value={addressIsCurrent} onChange={setAddressIsCurrent}/>
            {(addressIsCurrent==='no'||!data.applicationAddresses?.length)&&<label className="staff-form-field"><span className="staff-form-label">Your current address *</span><textarea className="staff-form-input" rows={4} value={currentAddress} onChange={e=>setCurrentAddress(e.target.value)} required placeholder="Enter your current residential address"/></label>}
            <YesNoSelect id="address-proof-provided" label="Have you provided proof of this current address to LAUREM Admin as part of your application?" value={addressProofProvided} onChange={setAddressProofProvided}/>
          </div>
        </div>

        {isVisaSwitch&&<div style={{marginTop:18,paddingTop:18,borderTop:'1px solid var(--line)'}}>
          <p className="staff-eyebrow">UK right to work</p>
          <div className="staff-form-grid">
            <YesNoSelect id="right-to-work-status" label="Do you currently have the right to work in the UK?" value={rightToWorkStatus} onChange={setRightToWorkStatus}/>
            <YesNoSelect id="right-to-work-proof" label="Have you provided your right-to-work proof to LAUREM Admin as part of your application?" value={rightToWorkProofProvided} onChange={setRightToWorkProofProvided}/>
          </div>
          {showShareCode&&<label className="staff-form-field" style={{marginTop:12}}><span className="staff-form-label">UK status share code *</span><input className="staff-form-input" value={ukStatusShareCode} onChange={e=>setUkStatusShareCode(e.target.value.toUpperCase())} maxLength={40} autoComplete="off" required placeholder="Enter your UK share code"/><span className="staff-card-copy">Provide the share code you have been issued so LAUREM Admin can check your current UK status and right-to-work position.</span></label>}
        </div>}

        <StaffAction primary type="submit" disabled={busy}>{busy?'Saving…':'Save sponsorship details'}</StaffAction>
      </form>
    </StaffPanel>
    <StaffPanel><StaffSectionHeader title="Case readiness" copy="This checklist confirms whether the information you supplied and the LAUREM payment requirement are complete. It is not a statement of UK immigration eligibility."/><div className="staff-readiness-list">{(data.readiness?.items||[]).map(item=><div key={item.key}><StaffBadge tone={item.ready?'live':'attention'}>{item.ready?'Ready':'Action needed'}</StaffBadge><span>{item.label}</span></div>)}</div>{!!data.readiness?.missing.length&&<StaffNotice tone="warning"><p>Complete the items marked Action needed. Passport, address and UK right-to-work information is supplied by you; the sponsorship-support invoice is completed through payment.</p></StaffNotice>}</StaffPanel>
    <StaffPanel><StaffSectionHeader title="Certificate of Sponsorship" copy="Your CoS will appear here when LAUREM has uploaded it to your private Staff Portal."/><div className="staff-cos-list">{data.visaDocuments.length===0?<div className="staff-empty">No CoS document is currently available.</div>:data.visaDocuments.map((doc:any)=><article key={doc.id}><div><strong>{doc.title}</strong><span>{doc.original_filename||doc.mime_type} · Uploaded {fmt(doc.issued_at)}</span></div><a href={'/api/staff/documents/'+encodeURIComponent(doc.id)+'/download'} download className="staff-action-primary">Download</a></article>)}</div>{c.sms_reference&&<p className="staff-card-copy">SMS reference: <strong>{c.sms_reference}</strong></p>}{c.cos_number&&<p className="staff-card-copy">CoS number: <strong>{c.cos_number}</strong></p>}</StaffPanel>
    <StaffPanel><StaffSectionHeader title="Case timeline"/>{!data.events.length?<div className="staff-empty">No case events yet.</div>:<div className="staff-timeline">{data.events.map((event:any)=><article key={event.id}><div className="staff-timeline-dot" aria-hidden="true"/><div><strong>{event.event_type.replaceAll('_',' ')}</strong><span>{fmt(event.created_at)} · {event.actor_type}</span></div></article>)}</div>}</StaffPanel>
  </>}
 </StaffPageInner></StaffPage>;
}
