'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { StaffAction, StaffBadge, StaffLoading, StaffNotice, StaffPage, StaffPageHeader, StaffPageInner, StaffPanel, StaffSectionHeader, StaffMetric } from '@/components/StaffPortalUI';
type LeaveRequest={id:string;leave_type:string;start_date:string;end_date:string;total_days:number;reason:string|null;status:string;review_note:string|null;reviewed_at:string|null;created_at:string};
function date(v:string){return new Date(v+'T00:00:00').toLocaleDateString('en-GB',{dateStyle:'medium'});}function tone(v:string){return v==='approved'?'live':v==='rejected'||v==='cancelled'?'danger':v==='pending'?'attention':'neutral';}
export default function StaffLeavePage(){
 const router=useRouter();const[rows,setRows]=useState<LeaveRequest[]>([]);const[leaveType,setLeaveType]=useState('Annual Leave');const[startDate,setStartDate]=useState('');const[endDate,setEndDate]=useState('');const[reason,setReason]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[saved,setSaved]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/leave',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Unable to load leave requests.');setRows(b.requests||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load leave requests.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 async function submit(e:FormEvent){e.preventDefault();setBusy('submit');setSaved(false);setError('');try{const r=await fetch('/api/staff/leave',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leaveType,startDate,endDate,reason})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Unable to submit leave request.');setStartDate('');setEndDate('');setReason('');setSaved(true);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to submit leave request.');}finally{setBusy('');}}
 async function cancel(id:string){setBusy(id);setError('');try{const r=await fetch('/api/staff/leave?id='+encodeURIComponent(id),{method:'PATCH'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Unable to cancel leave request.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to cancel leave request.');}finally{setBusy('');}}
 const pending=useMemo(()=>rows.filter(r=>r.status==='pending').length,[rows]);const approved=useMemo(()=>rows.filter(r=>r.status==='approved').length,[rows]);
 if(loading)return <StaffLoading label="Loading leave requests…"/>;
 return <StaffPage className="staff-page--leave"><StaffPageInner><StaffPageHeader eyebrow="Workforce leave" title="My Leave" subtitle="Request time away from work and track LAUREM's decisions." actions={<StaffAction onClick={()=>void load()}>Refresh</StaffAction>}/>{error&&<StaffNotice tone="danger"><strong>Leave update failed</strong><p>{error}</p></StaffNotice>}{saved&&<StaffNotice tone="success">Your leave request has been submitted to LAUREM for review.</StaffNotice>}
 <div className="staff-stat-grid"><StaffMetric label="Requests" value={rows.length}/><StaffMetric label="Pending" value={pending}/><StaffMetric label="Approved" value={approved}/></div>
 <div className="staff-workforce-grid"><StaffPanel><StaffSectionHeader title="Request leave" copy="Submit a request with dates and enough context for LAUREM to review it."/><form className="staff-modern-form" onSubmit={submit}><label className="staff-form-field"><span className="staff-form-label">Leave type</span><select className="staff-form-input" value={leaveType} onChange={e=>setLeaveType(e.target.value)}><option>Annual Leave</option><option>Sick Leave</option><option>Family Leave</option><option>Unpaid Leave</option><option>Other Leave</option></select></label><div className="staff-form-grid"><label className="staff-form-field"><span className="staff-form-label">Start date</span><input className="staff-form-input" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} required/></label><label className="staff-form-field"><span className="staff-form-label">End date</span><input className="staff-form-input" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} required/></label></div><label className="staff-form-field"><span className="staff-form-label">Reason or additional context</span><textarea className="staff-form-input" value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} rows={6} placeholder="Optional"/></label><StaffAction primary type="submit" disabled={busy==='submit'}>{busy==='submit'?'Submitting…':'Submit leave request'}</StaffAction></form></StaffPanel>
 <StaffPanel><StaffSectionHeader title="Leave history" copy="Submitted requests and LAUREM review decisions."/>
 {!rows.length?<div className="staff-empty">No leave requests have been submitted yet.</div>:<div className="staff-leave-list">{rows.map(row=><article className="staff-leave-card" key={row.id}><div className="staff-leave-top"><div><p className="staff-document-category">{row.leave_type.replaceAll('_',' ')}</p><h3>{date(row.start_date)} → {date(row.end_date)}</h3><span>{row.total_days} day{row.total_days===1?'':'s'}</span></div><StaffBadge tone={tone(row.status)}>{row.status.replaceAll('_',' ')}</StaffBadge></div>{row.reason&&<p className="staff-card-copy staff-preserve-whitespace">{row.reason}</p>}{row.review_note&&<div className="staff-review-note"><strong>LAUREM note</strong><span>{row.review_note}</span></div>}{['pending','approved'].includes(row.status)&&<StaffAction disabled={busy===row.id} onClick={()=>void cancel(row.id)}>{busy===row.id?'Cancelling…':'Cancel request'}</StaffAction>}</article>)}</div>}
 </StaffPanel></div>
 </StaffPageInner></StaffPage>;
}
