'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { StaffAction, StaffBadge, StaffLoading, StaffNotice, StaffPage, StaffPageHeader, StaffPageInner, StaffPanel, StaffSectionHeader, StaffMetric } from '@/components/StaffPortalUI';
type Period={period_start:string;period_end:string;pay_date:string|null;status:string};type Entry={id:string;payroll_period_id:string;approved_hours:number|null;hourly_rate:number|null;gross_amount:number|null;status:string;notes:string|null;payroll_periods?:Period|null};
function money(v:number|null){return v==null?'Not set':'£'+Number(v).toFixed(2);}function date(v:string|null){return v?new Date(v+'T00:00:00').toLocaleDateString('en-GB',{dateStyle:'medium'}):'Not set';}function tone(v:string){return v==='paid'||v==='approved'?'live':v==='rejected'||v==='failed'?'danger':v==='pending'?'attention':'neutral';}
export default function StaffPayrollPage(){
 const router=useRouter();const[entries,setEntries]=useState<Entry[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/payroll',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Unable to load payroll information.');setEntries(b.entries||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load payroll information.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 const totals=useMemo(()=>({gross:entries.reduce((s,e)=>s+(Number(e.gross_amount)||0),0),hours:entries.reduce((s,e)=>s+(Number(e.approved_hours)||0),0),paid:entries.filter(e=>e.status==='paid').length}),[entries]);
 if(loading)return <StaffLoading label="Loading payroll workspace…"/>;
 return <StaffPage className="staff-page--payroll"><StaffPageInner><StaffPageHeader eyebrow="Payroll" title="My payroll" subtitle="A clean record of approved hours, rates, gross payroll and pay-period status." actions={<StaffAction onClick={()=>void load()}>Refresh</StaffAction>}/>{error&&<StaffNotice tone="danger"><strong>Payroll unavailable</strong><p>{error}</p></StaffNotice>}
 <div className="staff-stat-grid"><StaffMetric label="Records" value={entries.length}/><StaffMetric label="Approved hours" value={totals.hours.toFixed(2)}/><StaffMetric label="Gross shown" value={money(totals.gross)}/><StaffMetric label="Paid periods" value={totals.paid}/></div>
 {!entries.length?<StaffPanel><StaffSectionHeader title="No payroll records yet" copy="Payroll entries will appear here once your approved hours are included in a payroll period."/><StaffAction href="/staff/timesheets" primary>Open My Timesheets</StaffAction></StaffPanel>:<StaffPanel><StaffSectionHeader title="Pay-period history" copy="Each record below reflects the payroll data currently available to your staff account."/><div className="staff-payroll-list">{entries.map(e=>{const p=e.payroll_periods;return <article className="staff-payroll-card" key={e.id}><div className="staff-payroll-top"><div><p className="staff-document-category">PAY PERIOD</p><h3>{p?date(p.period_start)+' to '+date(p.period_end):'Payroll period'}</h3><span>Pay date: {date(p?.pay_date||null)}</span></div><StaffBadge tone={tone(e.status)}>{e.status.replaceAll('_',' ')}</StaffBadge></div><div className="staff-payroll-grid"><div><span>Approved hours</span><strong>{e.approved_hours==null?'Not set':Number(e.approved_hours).toFixed(2)}</strong></div><div><span>Hourly rate</span><strong>{money(e.hourly_rate)}</strong></div><div><span>Gross amount</span><strong>{money(e.gross_amount)}</strong></div><div><span>Payroll state</span><strong>{p?.status?.replaceAll('_',' ')||'Not set'}</strong></div></div>{e.notes&&<div className="staff-payroll-note">{e.notes}</div>}</article>})}</div></StaffPanel>}
 </StaffPageInner></StaffPage>;
}
