export const LAUREM_CURRENT_UK_VISA_TYPES = [
  { value: 'Skilled Worker visa', label: 'Skilled Worker visa' },
  { value: 'Health and Care Worker visa', label: 'Health and Care Worker visa' },
  { value: 'Student visa', label: 'Student visa' },
  { value: 'Graduate visa', label: 'Graduate visa' },
  { value: 'Global Talent visa', label: 'Global Talent visa' },
  { value: 'Innovator Founder visa', label: 'Innovator Founder visa' },
  { value: 'Scale-up Worker visa', label: 'Scale-up Worker visa' },
  { value: 'High Potential Individual (HPI) visa', label: 'High Potential Individual (HPI) visa' },
  { value: 'Global Business Mobility - Senior or Specialist Worker', label: 'Global Business Mobility - Senior or Specialist Worker' },
  { value: 'Global Business Mobility - Graduate Trainee', label: 'Global Business Mobility - Graduate Trainee' },
  { value: 'Global Business Mobility - Service Supplier', label: 'Global Business Mobility - Service Supplier' },
  { value: 'Global Business Mobility - UK Expansion Worker', label: 'Global Business Mobility - UK Expansion Worker' },
  { value: 'Global Business Mobility - Secondment Worker', label: 'Global Business Mobility - Secondment Worker' },
  { value: 'International Sportsperson visa', label: 'International Sportsperson visa' },
  { value: 'Minister of Religion visa', label: 'Minister of Religion visa' },
  { value: 'Creative Worker visa', label: 'Temporary Work - Creative Worker visa' },
  { value: 'Charity Worker visa', label: 'Temporary Work - Charity Worker visa' },
  { value: 'Religious Worker visa', label: 'Temporary Work - Religious Worker visa' },
  { value: 'Government Authorised Exchange Worker visa', label: 'Temporary Work - Government Authorised Exchange Worker visa' },
  { value: 'International Agreement Worker visa', label: 'Temporary Work - International Agreement Worker visa' },
  { value: 'Seasonal Worker visa', label: 'Seasonal Worker visa' },
  { value: 'Youth Mobility Scheme visa', label: 'Youth Mobility Scheme visa' },
  { value: 'India Young Professionals Scheme visa', label: 'India Young Professionals Scheme visa' },
  { value: 'UK Ancestry visa', label: 'UK Ancestry visa' },
  { value: 'British National (Overseas) visa', label: 'British National (Overseas) visa' },
  { value: 'Representative of an Overseas Business visa', label: 'Representative of an Overseas Business visa' },
  { value: 'Family visa - partner or spouse', label: 'Family visa - partner or spouse' },
  { value: 'Family visa - parent', label: 'Family visa - parent' },
  { value: 'Family visa - child', label: 'Family visa - child' },
  { value: 'Child Student visa', label: 'Child Student visa' },
  { value: 'Parent of a Child Student visa', label: 'Parent of a Child Student visa' },
  { value: 'Short-term study visa', label: 'Short-term study visa' },
  { value: 'Standard Visitor visa', label: 'Standard Visitor visa' },
  { value: 'EU Settlement Scheme - settled status', label: 'EU Settlement Scheme - settled status' },
  { value: 'EU Settlement Scheme - pre-settled status', label: 'EU Settlement Scheme - pre-settled status' },
  { value: 'Indefinite leave to remain / settlement', label: 'Indefinite leave to remain / settlement' },
  { value: 'No current UK immigration permission', label: 'No current UK immigration permission' },
  { value: 'Other / not listed', label: 'Other / not listed' },
] as const;
