import type { SupabaseClient } from '@supabase/supabase-js';
export const LAUREM_MESSAGE_NAMESPACES=['lauremcare','lauremnurse','lauremstaff'] as const;
export function namespaceForRole(role:string|null|undefined){const v=(role||'').toLowerCase();if(v.includes('nurse'))return'lauremnurse';if(v.includes('care')||v.includes('support')||v.includes('assistant'))return'lauremcare';return'lauremstaff';}
export function handleBase(name:string){const b=name.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').trim().split(/\s+/).join('.').replace(/[^a-z0-9.]/g,'.').replace(/\.{2,}/g,'.').replace(/^\.|\.$/g,'');return b||'staff';}
export async function ensureLauremMailbox(c:SupabaseClient,s:{id:string;full_name:string;job_title?:string|null}){const e=await c.from('staff_internal_mailboxes').select('id,staff_id,handle,namespace,enabled').eq('staff_id',s.id).maybeSingle();if(e.data)return e.data;const ns=namespaceForRole(s.job_title),base=handleBase(s.full_name);for(let i=1;i<=100;i++){const h=i===1?base:`${base}${i}`;const clash=await c.from('staff_internal_mailboxes').select('id').eq('handle',h).eq('namespace',ns).maybeSingle();if(clash.data)continue;const{data,error}=await c.from('staff_internal_mailboxes').insert({staff_id:s.id,handle:h,namespace:ns}).select('id,staff_id,handle,namespace,enabled').single();if(!error&&data){await c.from('staff_profiles').update({portal_handle:h,department_namespace:ns,portal_address:`${h}@${ns}`,updated_at:new Date().toISOString()}).eq('id',s.id);return data;}}throw new Error('Unable to allocate LAUREM internal address.');}
export async function findLauremStaffByAddress(c:SupabaseClient,address:string){const v=address.trim().toLowerCase().replace(/\s+/g,''),at=v.lastIndexOf('@');if(at<=0)return null;const h=v.slice(0,at),ns=v.slice(at+1);if(!LAUREM_MESSAGE_NAMESPACES.includes(ns as any))return null;const{data:m,error}=await c.from('staff_internal_mailboxes').select('staff_id,handle,namespace,enabled').eq('handle',h).eq('namespace',ns).eq('enabled',true).maybeSingle();if(error||!m)return null;const{data:s}=await c.from('staff_profiles').select('id,laurem_id,employee_number,full_name,email,job_title,employment_status').eq('id',m.staff_id).maybeSingle();if(!s||!['pending','active'].includes(s.employment_status))return null;return{...s,mailbox:m};}
export function directKey(a:string,b:string){return[a,b].sort().join(':');}
export async function getOrCreateConversation(c:SupabaseClient,a:string,b:string){const key=directKey(a,b),e=await c.from('staff_message_conversations').select('id,direct_key,created_at,updated_at,last_message_at').eq('direct_key',key).maybeSingle();if(e.data)return e.data;const{data:x,error}=await c.from('staff_message_conversations').insert({direct_key:key,created_by_staff_id:a}).select('id,direct_key,created_at,updated_at,last_message_at').single();if(error||!x){const retry=await c.from('staff_message_conversations').select('id,direct_key,created_at,updated_at,last_message_at').eq('direct_key',key).maybeSingle();if(retry.data)return retry.data;throw error||new Error('Unable to create conversation.');}const{error:pe}=await c.from('staff_message_participants').insert([{conversation_id:x.id,staff_id:a},{conversation_id:x.id,staff_id:b}]);if(pe)throw pe;return x;}
export async function participantConversationIds(c:SupabaseClient,id:string){const{data,error}=await c.from('staff_message_participants').select('conversation_id').eq('staff_id',id);if(error)throw error;return(data||[]).map((x:any)=>x.conversation_id);}
