'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { moneyGbp, visaPathwayLabel, type LauremVisaPathway } from '@/lib/laurem-visa-sponsorship';

type Data = { staff:any; application:any; case:any; invoice:any; events:any[]; visaDocuments:any[]; smsUrl:string };
const card:React.CSSProperties={background:'#fff',border:'1px solid #e5eaf0',borderRadius:16,padding:20};
const muted:React.CSSProperties={color:'var(--muted)'};
const button=(primary=false):React.CSSProperties=>({border:primary?'0':'1px solid var(--line)',background:primary?'var(--ink)':'#fff',color:primary?'#fff':'var(--ink)',borderRadius:9,padding:'10px 13px',fontWeight:800,cursor:'pointer',textDecoration:'none'});
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:10,border:'1px solid var(--line)',borderRadius:9,font:'inherit'};
function fmt(value:any){if(!value)return 'Not set';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});}
function badge(value:string){return <span style={{padding:'6px 9px',borderRadius:999,background:'var(--soft)',fontSize:12,fontWeight:800}}>{String(value||'Not set').replaceAll('_',' ')}</span>;}

export default function AdminVisaSponsorshipPage(){
 const params=useParams<{staffId:string}>(); const staffId=params.staffId;
 const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [status,setStatus]=useState(''); const [pathway,setPathway]=useState<LauremVisaPathway>('visa_switch'); const [smsReference,setSmsReference]=useState(''); const [cosNumber,setCosNumber]=useState(''); const [adminNotes,setAdminNotes]=useState(''); const [paymentReference,setPaymentReference]=useState('');
 async function load(){
  if(!staffId)return; setLoading(true); setError('');
  try{const r=await fetch('/api/admin/workforce/staff/'+encodeURIComponent(staffId)+'/visa-sponsorship',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load case.');setData(b);if(b.case){setStatus(b.case.status);setPathway(b.case.pathway);setSmsReference(b.case.sms_reference||'');setCosNumber(b.case.cos_number||'');setAdminNotes(b.case.admin_notes||'');}}catch(e){setError(e instanceof Error?e.message:'Unable to load case.');}finally{setLoading(false);}
 }
 useEffect(()=>{void load();},[staffId]);
 async function patch(extra:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await fetch('/api/admin/workforce/staff/'+encodeURIComponent(staffId)+'/visa-sponsorship',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,pathway,smsReference,cosNumber,adminNotes,...extra})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to update case.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update case.');}finally{setBusy(false);}}
 async function uploadCos(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const form=new FormData(e.currentTarget);form.set('title','Certificate of Sponsorship');form.set('category','visa_sponsorship');form.set('requiresSignature','false');const r=await fetch('/api/admin/workforce/staff/'+encodeURIComponent(staffId)+'/documents',{method:'POST',body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to upload CoS.');await load();e.currentTarget.reset();}catch(e){setError(e instanceof Error?e.message:'Unable to upload CoS.');}finally{setBusy(false);}}
 if(loading)return <main className='wrap' style={{padding:'36px 0 80px'}}><div className='card' style={{padding:20}}>Loading visa sponsorship workspace…</div></main>;
 if(!data)return <main className='wrap' style={{padding:'36px 0 80px'}}><Link href={'/admin/workforce/'+encodeURIComponent(staffId)}>← Staff 360</Link><div className='card' style={{padding:20,marginTop:18,color:'#8a2323'}}>{error||'Unable to load case.'}</div></main>;
 const c=data.case, invoice=data.invoice;
 return <main className='wrap' style={{padding:'30px 0 80px',maxWidth:1180}}>
  <Link href={'/admin/workforce/'+encodeURIComponent(staffId)} style={{color:'var(--muted)',textDecoration:'none'}}>← Staff 360</Link>
  <div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'flex-start',flexWrap:'wrap',marginTop:12}}><div><div style={{color:'var(--accent)',fontWeight:800,letterSpacing:'.08em'}}>VISA & SPONSORSHIP</div><h1 style={{margin:'5px 0'}}>{data.staff.full_name}</h1><div style={muted}>{data.staff.job_title} · {data.staff.employee_number}</div></div><a href={data.smsUrl} target='_blank' rel='noreferrer' style={button(true)}>Open Sponsor Management System</a></div>
 {error&&<div role='alert' className='card' style={{marginTop:16,padding:14,color:'#8a2323'}}>{error}</div>}
 {!c?<section className='card' style={{padding:20,marginTop:18}}><h2 style={{marginTop:0}}>No sponsorship request yet</h2><p style={muted}>The staff member has not requested visa support through the Staff Portal.</p></section>:<>{
  <section className='card' style={{padding:20,marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h2 style={{margin:'0 0 5px'}}>{visaPathwayLabel(c.pathway)}</h2><div style={muted}>Requested {fmt(c.requested_at)}</div></div>{badge(c.status)}</div><p style={{...muted,marginTop:8}}>{c.pathway_basis}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:16}}>
   <label style={{fontSize:12,fontWeight:800}}>Pathway<select value={pathway} onChange={e=>setPathway(e.target.value as LauremVisaPathway)} style={input}><option value='visa_switch'>Visa switch</option><option value='international_sponsorship'>International sponsorship</option></select></label>
   <label style={{fontSize:12,fontWeight:800}}>Case status<select value={status} onChange={e=>setStatus(e.target.value)} style={input}>{['requested','admin_review','awaiting_payment','preparing_sms','submitted_to_sms','cos_pending','cos_assigned','completed','declined','withdrawn'].map(s=><option key={s}>{s}</option>)}</select></label>
   <label style={{fontSize:12,fontWeight:800}}>SMS reference<input value={smsReference} onChange={e=>setSmsReference(e.target.value)} style={input}/></label>
   <label style={{fontSize:12,fontWeight:800}}>CoS number<input value={cosNumber} onChange={e=>setCosNumber(e.target.value)} style={input}/></label>
  </div><label style={{display:'block',fontSize:12,fontWeight:800,marginTop:12}}>Admin notes<textarea value={adminNotes} onChange={e=>setAdminNotes(e.target.value)} rows={4} style={{...input,resize:'vertical',marginTop:6}}/></label><button disabled={busy} onClick={()=>void patch()} style={{...button(true),marginTop:12}}>{busy?'Saving…':'Save case'}</button></section>
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.2fr) minmax(300px,.8fr)',gap:16,marginTop:16}}>
   <article className='card' style={{padding:20}}><h2 style={{marginTop:0}}>Recruitment information available to LAUREM</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:13}}>{[['Full name',data.application?.full_name],['DOB',data.application?.date_of_birth],['Nationality',data.application?.nationality],['Country',data.application?.current_country||data.application?.country_of_residence],['Role',data.application?.role_applied||data.staff.job_title],['Start date',data.application?.start_date||data.staff.start_date],['Living in UK',data.application?.living_in_uk],['Work permission',data.application?.work_permission],['Requires sponsorship',data.application?.requires_sponsorship],['Email',data.application?.email],['Phone',data.application?.phone],['Address',data.application?.address]].map(([label,value])=><div key={String(label)}><div style={muted}>{label}</div><strong>{value||'Not recorded'}</strong></div>)}</div></article>
   <article className='card' style={{padding:20}}><h2 style={{marginTop:0}}>Invoice</h2><div style={{fontSize:30,fontWeight:900}}>{moneyGbp(invoice?.amount_pence||200000)}</div><div style={{...muted,marginTop:4}}>{invoice?.invoice_number||'No invoice'}</div><div style={{marginTop:12}}>{badge(invoice?.status||'issued')}</div>{invoice?.status==='issued'&&<><label style={{display:'block',marginTop:14,fontSize:12,fontWeight:800}}>Payment reference<input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} style={{...input,marginTop:6}}/></label><button disabled={busy} onClick={()=>void patch({markPaid:true,paymentReference,paymentMethod:'admin-recorded'})} style={{...button(true),marginTop:10}}>Mark invoice paid</button></>}</article>
  </section>
  <section className='card' style={{padding:20,marginTop:16}}><h2 style={{marginTop:0}}>Certificate of Sponsorship upload</h2><p style={muted}>Upload the CoS into this staff account. It remains private and becomes downloadable from the candidate's Staff Portal.</p><form onSubmit={uploadCos} style={{display:'grid',gap:10,maxWidth:620}}><input name='file' type='file' accept='.pdf,.txt,.md,.png,.jpg,.jpeg,application/pdf,text/plain,text/markdown,image/png,image/jpeg' required/><button disabled={busy} style={{...button(true),justifySelf:'start'}}>{busy?'Uploading…':'Upload CoS to staff portal'}</button></form><div style={{display:'grid',gap:9,marginTop:16}}>{data.visaDocuments.map(doc=><div key={doc.id} style={{padding:12,border:'1px solid var(--line)',borderRadius:10}}><strong>{doc.title}</strong><div style={muted}>{doc.original_filename||doc.mime_type} · {fmt(doc.issued_at)} · {doc.status}</div></div>)}{!data.visaDocuments.length&&<div style={muted}>No CoS document uploaded yet.</div>}</div></section>
  <section className='card' style={{padding:20,marginTop:16}}><h2 style={{marginTop:0}}>SMS / case timeline</h2><div style={{display:'grid',gap:8}}>{data.events.map(event=><div key={event.id} style={{padding:'10px 0',borderTop:'1px solid var(--line)'}}><strong>{event.event_type.replaceAll('_',' ')}</strong><div style={muted}>{fmt(event.created_at)} · {event.actor_type} · {event.actor}</div></div>)}{!data.events.length&&<div style={muted}>No events recorded.</div>}</div></section>
 </>}
 </main>;
}