'use client';
import { FormEvent,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { StaffAction,StaffBadge,StaffLoading,StaffNotice,StaffPage,StaffPageHeader,StaffPageInner,StaffPanel,StaffSectionHeader } from '@/components/StaffPortalUI';
type Rota={id:string;effective_from:string;stable_shift_preference:boolean;regions:string[];shift_preferences:string[];care_settings:string[];preferred_training_location:string|null;driver_available:boolean;notes:string|null;status:string;review_note:string|null};
const regions=['London','West Midlands','Manchester','Glasgow'];
const trainingLocations=['Birmingham','London','Glasgow','Manchester'];
const shifts=[['day','Day shifts'],['night','Night shifts'],['either','Day or night']] as const;
const settings=[['care_home','Care home'],['supported_living','Supported living / 1-to-1'],['live_in_care','Live-in care'],['shared_lives','Shared Lives / adult placement'],['home_care','Domiciliary / home care'],['community_care_calls','Community care calls / double-up']] as const;
function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London'}).format(new Date());}
function futureLocalDate(days:number){const d=new Date();d.setDate(d.getDate()+days);return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London'}).format(d);}
function toggle(a:string[],v:string){return a.includes(v)?a.filter(x=>x!==v):a.concat(v);}
function date(v:string){return new Date(v+'T00:00:00').toLocaleDateString('en-GB',{dateStyle:'medium'});}
export default function StaffRotaPreferencesPage(){
 const router=useRouter();const[current,setCurrent]=useState<Rota|null>(null);const[history,setHistory]=useState<Rota[]>([]);const[effectiveFrom,setEffectiveFrom]=useState(localDate());const[selectedRegions,setSelectedRegions]=useState<string[]>([]);const[shiftPreferences,setShiftPreferences]=useState<string[]>(['day']);const[careSettings,setCareSettings]=useState<string[]>(['care_home']);const[trainingLocation,setTrainingLocation]=useState('');const[stableShift,setStableShift]=useState(true);const[driverAvailable,setDriverAvailable]=useState(false);const[notes,setNotes]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[saved,setSaved]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/rota',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load rota preferences.');setCurrent(b.current||null);setHistory(b.history||[]);if(b.current&&b.current.status==='requested'){setEffectiveFrom(b.current.effective_from);setSelectedRegions(b.current.regions||[]);setShiftPreferences(b.current.shift_preferences||[]);setCareSettings(b.current.care_settings||[]);setTrainingLocation(b.current.preferred_training_location||'');setStableShift(Boolean(b.current.stable_shift_preference));setDriverAvailable(Boolean(b.current.driver_available));setNotes(b.current.notes||'');}}catch(e){setError(e instanceof Error?e.message:'Unable to load rota preferences.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 const reviewedCurrent=Boolean(current&&current.status!=='requested');
 function startNewRequest(){setEffectiveFrom(futureLocalDate(1));setSelectedRegions([]);setShiftPreferences(['day']);setCareSettings(['care_home']);setTrainingLocation('');setStableShift(true);setDriverAvailable(false);setNotes('');setSaved(false);setError('');}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setSaved(false);setError('');try{const r=await fetch('/api/staff/rota',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({effectiveFrom,regions:selectedRegions,shiftPreferences,careSettings,trainingLocation,stableShift,driverAvailable,notes})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to save rota request.');await load();setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Unable to save rota request.');}finally{setBusy(false);}}
 if(loading)return <StaffLoading label="Loading work preferences…"/>;
 return <StaffPage className="staff-page--preferences"><StaffPageInner>
  <StaffPageHeader eyebrow="Work preferences" title="Tell LAUREM how you want to work" subtitle="Set preferred regions, shifts, care settings and your mandatory training location. Preferences guide matching but do not guarantee a particular placement." actions={<StaffAction onClick={()=>void load()}>Refresh</StaffAction>}/>
  {error&&<StaffNotice tone="danger"><strong>Preference update failed</strong><p>{error}</p></StaffNotice>}{saved&&<StaffNotice tone="success">Rota request saved.</StaffNotice>}
  {reviewedCurrent&&<StaffNotice tone="warning"><strong>Your latest rota request has been reviewed by LAUREM.</strong><p>It is read-only. Create a new request with a new effective date to change your preferences.</p><StaffAction onClick={startNewRequest} primary>Create new rota request</StaffAction></StaffNotice>}
  <div className="staff-workforce-grid"><StaffPanel><StaffSectionHeader title={reviewedCurrent?'New rota request':'Rota request'} copy="Your selections help LAUREM match you to available contracted services."/><form className="staff-modern-form" onSubmit={save}>
   <label className="staff-form-field"><span className="staff-form-label">Effective from</span><input className="staff-form-input" type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)} required min={localDate()}/></label>
   <PreferenceGroup title="Where would you like to cover shifts?" options={regions} value={selectedRegions} toggle={setSelectedRegions} helper="Service coverage region" multiple/>
   <PreferenceGroup title="Training location" options={trainingLocations} value={trainingLocation?[trainingLocation]:[]} toggle={(v)=>setTrainingLocation(v[0]||'')} helper="Choose the city where you would like to attend your mandatory one-week training."/>
   <PreferenceGroup title="Preferred shifts" options={shifts} value={shiftPreferences} toggle={setShiftPreferences} multiple/>
   <PreferenceGroup title="Preferred care setting" options={settings} value={careSettings} toggle={setCareSettings} multiple/>
   <label className="staff-preference-toggle"><input type="checkbox" checked={stableShift} onChange={e=>setStableShift(e.target.checked)}/><span><strong>I prefer a stable shift / long-term posting</strong><small>Prefer the same placement and shift pattern where client contracts allow.</small></span></label>
   <label className="staff-preference-toggle"><input type="checkbox" checked={driverAvailable} onChange={e=>setDriverAvailable(e.target.checked)}/><span><strong>I can drive for community care calls</strong><small>Useful for double-up morning and afternoon visits where one team member needs to drive.</small></span></label>
   <label className="staff-form-field"><span className="staff-form-label">Additional scheduling notes</span><textarea className="staff-form-input" value={notes} onChange={e=>setNotes(e.target.value)} rows={5} maxLength={3000} placeholder="Preferred areas, travel limits, recurring availability or other scheduling context."/></label>
   <StaffAction primary type="submit" disabled={busy}>{busy?'Saving…':'Submit rota request'}</StaffAction>
  </form></StaffPanel>
  <aside><StaffPanel><StaffSectionHeader title="Current preference"/>{current?<div className="staff-preference-summary"><Summary label="Regions" value={current.regions.join(', ')||'None selected'}/><Summary label="Shifts" value={current.shift_preferences.join(', ')||'None selected'}/><Summary label="Care settings" value={current.care_settings.join(', ')||'None selected'}/><Summary label="Training" value={current.preferred_training_location||'Not selected'}/><Summary label="Stable shifts" value={current.stable_shift_preference?'Preferred':'Not required'}/><Summary label="Driver" value={current.driver_available?'Available':'Not marked available'}/><Summary label="Status" value={current.status.replaceAll('_',' ')}/><div className="staff-preference-effective">Effective {date(current.effective_from)}</div>{current.review_note&&<div className="staff-review-note"><strong>LAUREM note</strong><span>{current.review_note}</span></div>}</div>:<div className="staff-empty">No rota preference has been submitted yet.</div>}</StaffPanel><StaffPanel><StaffSectionHeader title="How matching works"/><p className="staff-card-copy">LAUREM matches your preferences with live contracts and workforce requirements. Preferences do not guarantee a particular client, care setting, shift, location or number of hours.</p></StaffPanel></aside></div>
  <StaffPanel><StaffSectionHeader title="Preference history" copy="Previous requests remain visible so you can see how your preferences changed."/><div className="staff-preference-history">{!history.length?<div className="staff-empty">No previous rota requests.</div>:history.map(item=><article key={item.id}><div><strong>{item.regions.join(', ')||'No region'}</strong><span>{item.shift_preferences.join(', ')||'No shift preference'} · {date(item.effective_from)}</span></div><StaffBadge tone={item.status==='approved'?'live':item.status==='rejected'?'danger':'attention'}>{item.status.replaceAll('_',' ')}</StaffBadge></article>)}</div></StaffPanel>
 </StaffPageInner></StaffPage>;
}
function PreferenceGroup({title,options,value,toggle,helper,multiple=false}:{title:string;options:any[];value:string[];toggle:(v:string[])=>void;helper?:string;multiple?:boolean}){
 return <fieldset className="staff-preference-group"><legend>{title}</legend><div className="staff-preference-options">{options.map((option:any)=>{const k=Array.isArray(option)?option[0]:option;const label=Array.isArray(option)?option[1]:option;const checked=value.includes(k);return <label key={k} className={checked?'is-selected':''}><input type={multiple?'checkbox':'radio'} name={title} checked={checked} onChange={()=>toggle(multiple?toggleValue(value,k):[k])}/><span><strong>{label}</strong>{helper&&<small>{helper}</small>}</span></label>;})}</div></fieldset>;
}
function toggleValue(a:string[],v:string){return toggle(a,v);}
function Summary({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
