'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { StaffAction, StaffBadge, StaffLoading, StaffNotice, StaffPage, StaffPageHeader, StaffPageInner, StaffPanel, StaffSectionHeader } from '@/components/StaffPortalUI';
interface Task{id:string;task_key:string;category:string;title:string;description:string|null;required:boolean;status:'pending'|'completed'|'waived';document_path:string|null;acknowledgement_required:boolean;acknowledged_at:string|null;completed_at:string|null;}
interface PackageRow{id:string;audience:string;title:string;status:'pending'|'in_progress'|'complete';assigned_at:string;completed_at:string|null;}
const guidance:Record<string,{heading:string;text:string}>={identity_and_rtw:{heading:'LAUREM verification required',text:'LAUREM Compliance/HR must complete and record this identity and right-to-work verification. You do not need to self-certify this item in the Staff Portal.'},pvG_or_disclosure:{heading:'LAUREM disclosure check required',text:'LAUREM must confirm the applicable Scottish disclosure/PVG requirement and record its status before regulated work. You do not need to mark this item complete yourself.'}};
function date(v:string|null){return v?new Date(v).toLocaleDateString('en-GB',{dateStyle:'medium'}):'Not set';}
export default function StaffOnboardingPage(){
 const router=useRouter();const[packageRow,setPackageRow]=useState<PackageRow|null>(null);const[tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/onboarding',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load onboarding.');setPackageRow(b.package||null);setTasks(b.tasks||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load onboarding.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 async function acknowledge(taskId:string){setBusy(taskId);setError('');try{const r=await fetch('/api/staff/onboarding',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({taskId,action:'acknowledge'})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to acknowledge task.');setPackageRow(b.package);setTasks(cur=>cur.map(t=>t.id===taskId?b.task:t));}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge task.');}finally{setBusy(null);}}
 const required=useMemo(()=>tasks.filter(t=>t.required),[tasks]);const done=useMemo(()=>required.filter(t=>(t.status==='completed'||t.status==='waived')&&(!t.acknowledgement_required||Boolean(t.acknowledged_at))).length,[required]);const percent=required.length?Math.round(done/required.length*100):100;const pendingCompliance=tasks.filter(t=>guidance[t.task_key]&&t.status==='pending').length;
 if(loading)return <StaffLoading label="Loading onboarding centre…"/>;
 return <StaffPage className="staff-page--onboarding"><StaffPageInner>
  <StaffPageHeader eyebrow="Staff onboarding" title="Your onboarding centre" subtitle="Your assigned onboarding work, acknowledgements and LAUREM-controlled verification in one place." actions={<><StaffAction onClick={()=>void load()}>Refresh</StaffAction><StaffAction href="/staff/documents">Documents</StaffAction></>}/>
  {error&&<StaffNotice tone="danger"><strong>Onboarding update failed</strong><p>{error}</p></StaffNotice>}
  {!packageRow?<StaffPanel><StaffSectionHeader title="Nothing assigned yet" copy="Your onboarding package has not been assigned. Please contact LAUREM if you expected one."/></StaffPanel>:<>
   {pendingCompliance>0&&<StaffNotice tone="warning"><strong>Some verification items are still with LAUREM</strong><p>These items are controlled by LAUREM Compliance/HR and do not require employee acknowledgement. Your onboarding can continue while they are being reviewed, but they must be recorded before regulated work begins.</p></StaffNotice>}
   <div className="staff-onboarding-overview"><StaffPanel className="staff-onboarding-progress"><div className="staff-section-heading"><div><p className="staff-eyebrow">Current package</p><h2 className="staff-card-heading">{packageRow.title}</h2><p className="staff-card-copy">Assigned {date(packageRow.assigned_at)}</p></div><StaffBadge tone={packageRow.status==='complete'?'live':packageRow.status==='in_progress'?'attention':'neutral'}>{packageRow.status.replaceAll('_',' ')}</StaffBadge></div><div className="staff-progress-track" aria-label={percent + '% complete'}><div className="staff-progress-fill" style={{width:percent + '%'}}/></div><div className="staff-progress-meta"><strong>{percent}% complete</strong><span>{done}/{required.length} required tasks complete</span></div></StaffPanel>
   <StaffPanel><StaffSectionHeader title="What matters now"/><div className="staff-onboarding-next">{pendingCompliance>0?<><StaffBadge tone="attention">LAUREM action</StaffBadge><strong>Verification is still being recorded by LAUREM</strong><span>Continue with any employee acknowledgements that are ready.</span></>:percent===100?<><StaffBadge tone="live">Complete</StaffBadge><strong>Your required onboarding tasks are complete</strong><span>Keep checking your portal for future training or documents.</span></>:<><StaffBadge tone="attention">Your action</StaffBadge><strong>{required.length-done} required task{required.length-done===1?'':'s'} remaining</strong><span>Open the task list below and complete any outstanding acknowledgements.</span></>}</div></StaffPanel></div>
   <StaffPanel><StaffSectionHeader title="Onboarding tasks" copy="Each task clearly shows whether it needs you or LAUREM."/><div className="staff-onboarding-list">{tasks.map(task=>{const g=guidance[task.task_key];const pending=Boolean(g&&task.status==='pending');return <article className="staff-onboarding-task" key={task.id}><div className="staff-onboarding-task-main"><div className="staff-document-category">{task.category}</div><h3>{task.title}</h3><p>{task.description||'Review this onboarding item and complete the required action.'}</p>{g&&<div className="staff-task-guidance"><strong>{g.heading}</strong><span>{g.text}</span></div>}{task.document_path&&<a className="staff-task-link" href={'/' + task.document_path} target="_blank" rel="noreferrer">Open assigned material ↗</a>}</div><div className="staff-onboarding-task-side"><StaffBadge tone={pending?'attention':task.status==='completed'||task.status==='waived'?'live':'neutral'}>{pending?'Awaiting LAUREM':task.status}</StaffBadge>{task.required&&<span className="staff-task-required">Required</span>}{task.acknowledgement_required&&!task.acknowledged_at&&<StaffAction primary disabled={busy===task.id} onClick={()=>void acknowledge(task.id)}>{busy===task.id?'Saving…':'I have read and acknowledge'}</StaffAction>}{task.acknowledgement_required&&task.acknowledged_at&&<span className="staff-task-complete">Acknowledged {date(task.acknowledged_at)}</span>}{!task.acknowledgement_required&&<span className="staff-task-complete">{pending?'Awaiting LAUREM to complete this verification':'No employee acknowledgement required'}</span>}</div></article>})}</div></StaffPanel>
  </>}
 </StaffPageInner></StaffPage>;
}
