'use client';
import{useEffect,useState}from'react';import{useRouter}from'next/navigation';
import{StaffAction,StaffBadge,StaffLoading,StaffMetric,StaffNotice,StaffPage,StaffPageHeader,StaffPageInner,StaffPanel,StaffSectionHeader}from'@/components/StaffPortalUI';
const money=(p:number)=>'£'+(Number(p||0)/100).toFixed(2);
export default function StaffCompliancePage(){
 const router=useRouter();const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[saved,setSaved]=useState(false);const[status,setStatus]=useState('');const[checkDate,setCheckDate]=useState('');const[expiryDate,setExpiryDate]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/staff/compliance',{cache:'no-store'});if(r.status===401){router.replace('/staff/login');return;}const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load compliance.');setData(b);setStatus(b.staff?.dbs_pvg_status||'');setCheckDate(b.staff?.dbs_pvg_check_date||'');setExpiryDate(b.staff?.dbs_pvg_expiry_date||'');}catch(e){setError(e instanceof Error?e.message:'Unable to load compliance.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[router]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setSaved(false);setError('');try{const r=await fetch('/api/staff/compliance',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,checkDate,expiryDate})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to save.');setSaved(true);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 async function apply(type:'dbs'|'pvg'){setBusy(true);setError('');try{const r=await fetch('/api/staff/compliance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to create request.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create request.');}finally{setBusy(false);}}
 if(loading)return <StaffLoading label="Loading DBS and PVG…"/>;
 const open=data?.current||[];const verified=status==='current'||status==='under_review';const openRequests=open.length;
 return <StaffPage className="staff-page--compliance"><StaffPageInner><StaffPageHeader eyebrow="Compliance" title="DBS & PVG" subtitle="See your disclosure status, open requests and the actions LAUREM needs from you." actions={<StaffAction onClick={()=>void load()}>Refresh</StaffAction>}/>{error&&<StaffNotice tone="danger"><strong>Compliance update failed</strong><p>{error}</p></StaffNotice>}{saved&&<StaffNotice tone="success">Compliance details saved.</StaffNotice>}
 <div className="staff-stat-grid"><StaffMetric label="Record status" value={status?status.replaceAll('_',' '):'Not recorded'}/><StaffMetric label="Open requests" value={openRequests}/></div>
 <div className="staff-workforce-grid"><StaffPanel><StaffSectionHeader title="Your DBS / PVG record" copy="This is your reported record. LAUREM verification is separate and controls verified statuses."/><form className="staff-modern-form" onSubmit={save}><label className="staff-form-field"><span className="staff-form-label">Status</span><select className="staff-form-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Not recorded</option><option value="missing">Missing</option><option value="pending">Pending</option><option value="current" disabled>Current (LAUREM verified)</option><option value="expiring_soon">Expiring soon</option><option value="expired">Expired</option><option value="under_review" disabled>Under review (LAUREM verified)</option></select></label><div className="staff-form-grid"><label className="staff-form-field"><span className="staff-form-label">Check / issue date</span><input className="staff-form-input" type="date" value={checkDate} onChange={e=>setCheckDate(e.target.value)} disabled={verified}/></label><label className="staff-form-field"><span className="staff-form-label">Review / expiry date</span><input className="staff-form-input" type="date" value={expiryDate} onChange={e=>setExpiryDate(e.target.value)} disabled={verified}/></label></div><p className="staff-card-copy">For DBS, this is your reported review date rather than a government-set certificate expiry. LAUREM updates verified status separately.</p><StaffAction primary type="submit" disabled={busy||verified}>{verified?'Verified by LAUREM':'Save compliance details'}</StaffAction></form></StaffPanel>
 <aside><StaffPanel className="staff-compliance-apply"><StaffSectionHeader title="Apply through LAUREM" copy="Request the applicable disclosure process from one place."/><div className="staff-compliance-fees"><Fee label="Apply for DBS through LAUREM" fee={money(data.fees?.dbs?.amountPence||0)} note={data.fees?.dbs?.label} onClick={()=>void apply('dbs')} disabled={busy}/><Fee label="Apply for PVG through LAUREM" fee={money(data.fees?.pvg?.amountPence||0)} note={data.fees?.pvg?.label} onClick={()=>void apply('pvg')} disabled={busy}/></div><p className="staff-card-copy">The invoice uses the official disclosure fee applicable on the request date. No LAUREM administration fee is added. PVG waiver eligibility is confirmed by LAUREM before submission.</p></StaffPanel></aside></div>
 <StaffPanel><StaffSectionHeader title="Open requests & invoices"/>{!open.length?<div className="staff-empty">No open requests.</div>:<div className="staff-compliance-list">{open.map((x:any)=><article key={x.id}><div><strong>{String(x.compliance_type).toUpperCase()}</strong><span>{x.invoice_number}</span></div><StaffBadge tone={x.status==='paid'||x.status==='approved'?'live':'attention'}>{x.status}</StaffBadge><p>{money(x.amount_pence)} · Issued {x.issue_date}{x.due_date?' · Due '+x.due_date:''}</p>{x.details?.official_fee_note&&<small>{x.details.official_fee_note}</small>}</article>)}</div>}</StaffPanel>
 </StaffPageInner></StaffPage>;
}
function Fee({label,fee,note,onClick,disabled}:{label:string;fee:string;note?:string;onClick:()=>void;disabled:boolean}){return <article className="staff-compliance-fee"><div><strong>{label}</strong><span>{fee}</span><small>{note}</small></div><StaffAction primary onClick={onClick} disabled={disabled}>{label}</StaffAction></article>}
