'use client';

import Link from 'next/link';
import { useState } from 'react';
import { StaffAction, StaffLoading, StaffNotice, StaffPage, StaffPageInner, StaffPanel, StaffSectionHeader } from '@/components/StaffPortalUI';

export default function StaffChangePasswordPage(){
 const[currentPassword,setCurrentPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 async function submit(event:React.FormEvent){event.preventDefault();setError('');setMessage('');if(newPassword!==confirmPassword){setError('New passwords do not match.');return;}if(newPassword.length<10){setError('Use a password of at least 10 characters.');return;}setBusy(true);try{const response=await fetch('/api/staff/auth/change-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to change your password.');setMessage(body.message||'Password changed. Please sign in again.');setCurrentPassword('');setNewPassword('');setConfirmPassword('');}catch(e){setError(e instanceof Error?e.message:'Unable to change your password.');}finally{setBusy(false);}}
 return <StaffPage className="staff-page--security"><StaffPageInner><div className="staff-security-wrap"><div className="staff-security-heading"><p className="staff-eyebrow">Account security</p><h1 className="staff-page-title">Change your Staff Portal password</h1><p className="staff-page-subtitle">Changing your password signs out every existing Staff Portal session.</p></div><StaffPanel><StaffSectionHeader title="Update password" copy="Use a strong password you do not reuse elsewhere." />{error&&<StaffNotice tone="danger"><strong>Password change failed</strong><p>{error}</p></StaffNotice>}{message&&<StaffNotice tone="success">{message}</StaffNotice>}<form className="staff-modern-form" onSubmit={submit}><label className="staff-form-field"><span className="staff-form-label">Current password</span><input className="staff-form-input" type="password" autoComplete="current-password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label className="staff-form-field"><span className="staff-form-label">New password</span><input className="staff-form-input" type="password" autoComplete="new-password" minLength={10} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label className="staff-form-field"><span className="staff-form-label">Confirm new password</span><input className="staff-form-input" type="password" autoComplete="new-password" minLength={10} required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><StaffAction primary type="submit" disabled={busy}>{busy?'Changing password…':'Change password'}</StaffAction></form><div className="staff-security-links"><Link href="/staff/profile">← Back to profile</Link><Link href="/staff">Staff Portal home</Link><Link href="/staff/password-reset">Forgot password?</Link></div></StaffPanel></div></StaffPageInner></StaffPage>;
}
